[project]
name = "decorator_intro"
version = "1.0.0"
description = "Introduction to Python decorator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.30.1",
    "loguru>=0.7.3",
]
